//<auto-generated/>
using System;
using System.Linq;
using TFX.Core.Model;
using Microsoft.Extensions.DependencyInjection;
using TFX.Core.Cache;
using TFX.App.INF.Servisses;
using TFX.App.MDL.Servisses;

namespace TFX.App.INF
{
    public class TFXAppINFModule : XModule
    {
        public override void Initialize(IServiceCollection pServices)
        {
            pServices.AddTransient<IRequestTestService, RequestTestService>();
            pServices.AddDbContext<RequestTestService.DBContext>();
            XMainCache.Add<RequestTestServiceModel>(RequestTestServiceModel.CID);
        }
    }
}