//<auto-generated/>
using System;
using System.Linq;
using TFX.Core.Model;
using Microsoft.Extensions.DependencyInjection;
using TFX.Core.Cache;

namespace TFX.App.RLE
{
    public class TFXAppRLEModule : XModule
    {
        public override void Initialize(IServiceCollection pServices)
        {
        }
    }
}